### PR TITLE
Section for security challenges.

### LINKED ISSUE #1: Add Ethical Hacking Resources
Kindly add resources related to **Ethical Hacking**. These can be study materials, links, question papers, tools etc.
Please make sure you add everything in a **separate specified folder**.

### PR DESCRIPTION
**Pull request by Prakhar0409**
#### Checklist

- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

**Changes proposed in this pull request**
- Added a section in README for security challenges giving a more hands on experience in ethical hacking
- Put in a **CodePath Security Shepherd Challenge** to try out

**Screenshots (if appropriate)** 

**Link to live demo (if appropriate):** 

**Closes #**

### CODE REVIEW

**Comment by yashovardhanagrawal** [comment]
@Prakhar0409 Thanks for the PR
I just edited your "Fixed #" tag as it will unnecessarily close the issue.
Let others review first, then we are ready for a merge here 😄

**Comment by Prakhar0409** [comment]
@yashovardhanagrawal https://security.codepath.com would redirect you to the login page anyway.  The challenge taker needs to register (which is free) and then can access an interface that looks like https://imagebin.ca/v/3dOXdfqaPItB . Voila!

**Comment by divyanshu-rawat** [comment]
@Prakhar0409  👍

**Comment by yashovardhanagrawal** [comment]
@Prakhar0409 okay then sorry for the inconvenience. 
Kindly resolve the conflicts.
@ihsraham will review it and merge it.

**Pull request merged**
